-- Sprint G/H: Block Missions
-- Per-program missions generated by AI and tracked for progress.

CREATE TABLE IF NOT EXISTS block_missions (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  program_id   text        NOT NULL,
  type         text        NOT NULL CHECK (type IN ('pr', 'consistency', 'volume', 'rpe')),
  description  text        NOT NULL,
  target       jsonb       NOT NULL,   -- { metric: string, value: number, unit: string }
  progress     jsonb       NOT NULL DEFAULT '{"current":0,"history":[]}',
  status       text        NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'failed')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

ALTER TABLE block_missions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own block_missions"
  ON block_missions
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS block_missions_user_program_idx
  ON block_missions(user_id, program_id);
